dnf support

diff --git a/version b/version
--- a/version
+++ b/version
@@ -167,6 +167,7 @@ function list_tools {
 }
 
 function try_pacman {
+  # is pacman installed?
   command -v pacman &> /dev/null 
   if [ $? -ne 0 ]
   then
@@ -175,6 +176,8 @@ function try_pacman {
 
   # pacman is installed. let's try it
   echo "version does not know about $1. Checking via pacman..."
+
+  # this will return non-zero if nothing is found
   result="$(pacman -Qi $1 2>/dev/null | grep -Ee 'Version')"
   if [ $? -eq 0 ]
   then
@@ -185,8 +188,8 @@ function try_pacman {
   exit 2
 }
 
-
 function try_apt {
+  # is apt installed?
   command -v apt &> /dev/null
   if [ $? -ne 0 ]
   then
@@ -195,6 +198,8 @@ function try_apt {
 
   # apt is installed. let's try it
   echo "version does not know about $1. Checking via apt..."
+
+  # this returns 0 even if no results, so we have to count the matched lines
   lines=$(apt list $1 --installed 2>/dev/null | grep -Ece $1)
   if [ $lines -gt 0 ]
   then
@@ -205,6 +210,27 @@ function try_apt {
   exit 2
 }
 
+function try_dnf {
+  # is dnf installed?
+  command -v dnf &> /dev/null
+  if [ $? -ne 0 ]
+  then
+    return
+  fi
+
+  # dnf is installed. let's try it
+  echo "version does not know about $1. Checking via dnf..."
+
+  # this will return non-zero if nothing is found
+  result="$(dnf list installed $1 2>/dev/null | grep -Ee $1)"
+  if [ $? -eq 0 ]
+  then
+    echo $result | sed -Ene "s/[^ ]+ +([^ ]*).*/$1 version: \1/p"
+    exit
+  fi
+  echo "$1 was not installed via dnf."
+  exit 2
+}
 
 # User forgot to specify the program or a flag
 if [ -z $1 ]
@@ -258,9 +284,14 @@ version_arg=${!tool}
 # do we know about this program?
 if [ -z $version_arg ]
 then
+  # maybe a package manager knows it
   try_pacman $1
   try_apt $1
+  try_dnf $1
+
+  # should only get here if neither pacman or apt are installed
   echo "version does not know about $1."
+  exit
 fi
 
 # display the correct command for the user
@@ -275,4 +306,3 @@ fi
 
 # success. make the call to display the version.
 $1 $version_arg
-
